[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  gin66/FastAccelStepper

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3
build_flags =
  -D MOTOR_BOARD_XIAO_ESP32S3
  -D MOTOR_PIN_DIR=D8
  -D MOTOR_PIN_STEP=D9
  -D MOTOR_PIN_MS1=D0
  -D MOTOR_PIN_MS2=D1
  -D MOTOR_PIN_MS3=D2
  -D MOTOR_PIN_EN=D3

[env:esp32dev]
board = esp32dev
build_flags =
  -D MOTOR_BOARD_ESP32DEV
  -D MOTOR_PIN_DIR=26
  -D MOTOR_PIN_STEP=25
  -D MOTOR_PIN_MS1=14
  -D MOTOR_PIN_MS2=27
  -D MOTOR_PIN_MS3=33
  -D MOTOR_PIN_EN=32
